# Generated by Django 6.0.5 on 2026-05-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('fecha', models.DateField(verbose_name='Fecha de Clase')),
                ('docente', models.CharField(max_length=100, verbose_name='Nombre del Docente')),
                ('foto_curso', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen del Curso')),
                ('hora_inicio', models.TimeField(default='08:00', verbose_name='Hora de Inicio')),
                ('aula', models.CharField(default='A-101', max_length=50, verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=100, verbose_name='Nombre del Alumno')),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tardanza'), ('J', 'Justificado')], max_length=1, verbose_name='Estado de Asistencia')),
                ('foto_alumno', models.ImageField(blank=True, null=True, upload_to='alumnos/', verbose_name='Foto del Alumno')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.clase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
