# Generated by Django 6.0.5 on 2026-05-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='foto_alumno',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='foto_curso',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Ej: https://ejemplo.com/foto-alumno.jpg', null=True, verbose_name='Link de la Foto'),
        ),
        migrations.AddField(
            model_name='clase',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Ej: https://ejemplo.com/imagen.jpg', null=True, verbose_name='Link de la Imagen'),
        ),
    ]
